//! Extracts a [`SongData`] from a Renoise `.xrns` file.
//!
//! An `.xrns` is a zip archive containing `Song.xml` plus embedded sample audio under
//! `SampleData/InstrumentNN.../SampleNN....ext`. This mirrors the C# original's
//! `SongDataFactory.cs`, but walks only the XML paths actually consumed by the converters instead
//! of deserializing the entire Renoise schema (which the original did via a 42,000-line
//! XSD-autogenerated class we deliberately don't reproduce).

use std::io::Read;
use std::path::Path;

use roxmltree::{Document, Node};

use crate::error::{Error, Result};
use crate::model::{
    EnvelopeData, InstrumentData, LoopMode, MasterTrackLineData, PatternData, SampleData, SongData,
    TrackLineData,
};

/// Renoise's C-4 in its own 0-119 note numbering; used as the neutral base note when a sample
/// specifies none.
const DEFAULT_BASE_NOTE: i8 = 48;

pub fn extract_song_data(xrns_path: &Path) -> Result<SongData> {
    let file = std::fs::File::open(xrns_path)?;
    let mut archive = zip::ZipArchive::new(file)?;

    let song_xml = {
        let mut entry = archive
            .by_name("Song.xml")
            .map_err(|_| Error::MissingSongXml)?;
        let mut buf = String::new();
        entry.read_to_string(&mut buf)?;
        buf
    };

    let doc = Document::parse(&song_xml)?;
    let root = doc.root_element();

    let global = find_child(root, "GlobalSongData");

    let mut song = SongData {
        name: global
            .and_then(|n| find_child(n, "SongName"))
            .and_then(text)
            .unwrap_or_default(),
        lines_per_beat: global
            .and_then(|n| find_child(n, "LinesPerBeat"))
            .and_then(text)
            .and_then(|s| s.parse().ok())
            .unwrap_or(4),
        sample_offset_compatibility_mode: global
            .and_then(|n| find_child(n, "SampleOffsetCompatibilityMode"))
            .and_then(text)
            .map(|s| s == "true")
            .unwrap_or(false),
        pitch_compatibility_mode: global
            .and_then(|n| find_child(n, "PitchEffectsCompatibilityMode"))
            .and_then(text)
            .map(|s| s == "true")
            .unwrap_or(false),
        playback_engine_version: global
            .and_then(|n| find_child(n, "PlaybackEngineVersion"))
            .and_then(text)
            .and_then(|s| s.parse().ok())
            .unwrap_or(1),
        // Extracted for parity with the original but not consumed downstream (dead field there
        // too -- kept for fidelity/debugging, not load-bearing).
        ticks_per_line: global
            .and_then(|n| find_child(n, "TicksPerLine"))
            .and_then(text)
            .and_then(|s| s.parse().ok())
            .unwrap_or(6),
        initial_bpm: global
            .and_then(|n| find_child(n, "BeatsPerMin"))
            .and_then(text)
            .and_then(|s| s.parse().ok())
            .unwrap_or(125),
        ..Default::default()
    };

    if let Some(sequence) = find_child(root, "PatternSequence") {
        song.restart_position = find_child(sequence, "LoopSelection")
            .and_then(|n| find_child(n, "CursorPos"))
            .and_then(text)
            .and_then(|s| s.parse().ok())
            .unwrap_or(0);

        song.pattern_order_table = find_child(sequence, "SequenceEntries")
            .map(|entries| {
                entries
                    .children()
                    .filter(|n| n.has_tag_name("SequenceEntry"))
                    .filter_map(|entry| find_child(entry, "Pattern"))
                    .filter_map(text)
                    .filter_map(|s| s.parse().ok())
                    .collect()
            })
            .unwrap_or_default();
    }

    let tracks_node = find_child(root, "Tracks");
    let sequencer_tracks: Vec<Node> = tracks_node
        .map(|n| {
            n.children()
                .filter(|c| c.has_tag_name("SequencerTrack"))
                .collect()
        })
        .unwrap_or_default();

    song.num_channels = sequencer_tracks
        .iter()
        .map(|t| {
            find_child(*t, "NumberOfVisibleNoteColumns")
                .and_then(text)
                .and_then(|s| s.parse::<usize>().ok())
                .unwrap_or(1)
        })
        .sum();

    song.num_master_track_columns = tracks_node
        .and_then(|n| find_child(n, "SequencerMasterTrack"))
        .and_then(|n| find_child(n, "NumberOfVisibleEffectColumns"))
        .and_then(text)
        .and_then(|s| s.parse().ok())
        .unwrap_or(0);

    // Per-track visible note-column counts, needed to map a track's local column index to the
    // song-wide flattened channel index used everywhere else.
    let track_channel_widths: Vec<usize> = sequencer_tracks
        .iter()
        .map(|t| {
            find_child(*t, "NumberOfVisibleNoteColumns")
                .and_then(text)
                .and_then(|s| s.parse::<usize>().ok())
                .unwrap_or(1)
        })
        .collect();

    if let Some(instruments_node) = find_child(root, "Instruments") {
        song.instruments = instruments_node
            .children()
            .filter(|n| n.has_tag_name("Instrument"))
            .map(extract_instrument)
            .collect();
    }
    song.num_master_track_columns = song.num_master_track_columns.min(1);

    if let Some(pool) = find_child(root, "PatternPool") {
        if let Some(patterns_node) = find_child(pool, "Patterns") {
            song.patterns = patterns_node
                .children()
                .filter(|n| n.has_tag_name("Pattern"))
                .map(|p| extract_pattern(p, &track_channel_widths, song.num_master_track_columns))
                .collect();
        }
    }

    Ok(song)
}

fn find_child<'a, 'input>(node: Node<'a, 'input>, tag: &str) -> Option<Node<'a, 'input>> {
    node.children().find(|c| c.has_tag_name(tag))
}

fn text(node: Node) -> Option<String> {
    node.text().map(|s| s.trim().to_string())
}

fn extract_pattern(
    pattern: Node,
    track_channel_widths: &[usize],
    num_master_track_columns: usize,
) -> PatternData {
    let num_rows: usize = find_child(pattern, "NumberOfLines")
        .and_then(text)
        .and_then(|s| s.parse().ok())
        .unwrap_or(64);

    let num_channels: usize = track_channel_widths.iter().sum();

    let mut data = PatternData {
        num_rows,
        tracks_line_data: vec![TrackLineData::default(); num_rows * num_channels],
        master_track_line_data: vec![
            MasterTrackLineData::default();
            num_rows * num_master_track_columns
        ],
    };

    let Some(tracks) = find_child(pattern, "Tracks") else {
        return data;
    };

    let mut pattern_track_iter = tracks
        .children()
        .filter(|c| c.has_tag_name("PatternTrack") || c.has_tag_name("PatternMasterTrack"));

    // Renoise emits PatternTrack entries in the same order as SequencerTrack entries, followed
    // by exactly one PatternMasterTrack.
    for (track_index, &channel_width) in track_channel_widths.iter().enumerate() {
        let Some(pattern_track) = pattern_track_iter.next() else {
            break;
        };
        let channel_base: usize = track_channel_widths[..track_index].iter().sum();

        extract_pattern_track(
            pattern_track,
            channel_base,
            channel_width,
            num_rows,
            num_channels,
            &mut data.tracks_line_data,
        );
    }

    if let Some(master_track) = pattern_track_iter.next() {
        extract_master_track(
            master_track,
            num_rows,
            num_master_track_columns,
            &mut data.master_track_line_data,
        );
    }

    data
}

fn extract_pattern_track(
    pattern_track: Node,
    channel_base: usize,
    channel_width: usize,
    num_rows: usize,
    num_channels: usize,
    out: &mut [TrackLineData],
) {
    let Some(lines) = find_child(pattern_track, "Lines") else {
        return;
    };

    for line in lines.children().filter(|c| c.has_tag_name("Line")) {
        let row: usize = match line.attribute("index").and_then(|s| s.parse().ok()) {
            Some(r) if r < num_rows => r,
            _ => continue,
        };

        // Note columns: one cell per visible note sub-column of this track.
        if let Some(note_columns) = find_child(line, "NoteColumns") {
            for (col, note_col) in note_columns
                .children()
                .filter(|c| c.has_tag_name("NoteColumn"))
                .enumerate()
            {
                if col >= channel_width {
                    break;
                }
                let channel = channel_base + col;
                let idx = row * num_channels + channel;
                let Some(cell) = out.get_mut(idx) else {
                    continue;
                };

                cell.note = find_child(note_col, "Note").and_then(text);
                cell.instrument = find_child(note_col, "Instrument").and_then(text);
                cell.volume = find_child(note_col, "Volume").and_then(text);
                cell.panning = find_child(note_col, "Panning").and_then(text);
                cell.delay = find_child(note_col, "Delay").and_then(text);
                cell.is_set = cell.note.is_some()
                    || cell.instrument.is_some()
                    || cell.volume.is_some()
                    || cell.panning.is_some()
                    || cell.delay.is_some();
            }
        }

        // Only effect-column index 0 of a track is ever read (matches the original); its
        // number/value pair is spread across every note sub-column of this track.
        if let Some(effect_columns) = find_child(line, "EffectColumns") {
            if let Some(effect_col) = effect_columns
                .children()
                .find(|c| c.has_tag_name("EffectColumn"))
            {
                let number = find_child(effect_col, "Number")
                    .and_then(text)
                    .unwrap_or_else(|| "00".to_string());
                let value = find_child(effect_col, "Value")
                    .and_then(text)
                    .unwrap_or_else(|| "00".to_string());

                for col in 0..channel_width {
                    let channel = channel_base + col;
                    let idx = row * num_channels + channel;
                    if let Some(cell) = out.get_mut(idx) {
                        cell.effect_number = number.clone();
                        cell.effect_value = value.clone();
                        cell.is_set = true;
                    }
                }
            }
        }
    }
}

fn extract_master_track(
    master_track: Node,
    num_rows: usize,
    num_master_track_columns: usize,
    out: &mut [MasterTrackLineData],
) {
    if num_master_track_columns == 0 {
        return;
    }

    let Some(lines) = find_child(master_track, "Lines") else {
        return;
    };

    for line in lines.children().filter(|c| c.has_tag_name("Line")) {
        let row: usize = match line.attribute("index").and_then(|s| s.parse().ok()) {
            Some(r) if r < num_rows => r,
            _ => continue,
        };

        let Some(effect_columns) = find_child(line, "EffectColumns") else {
            continue;
        };
        let Some(effect_col) = effect_columns
            .children()
            .find(|c| c.has_tag_name("EffectColumn"))
        else {
            continue;
        };

        let number = find_child(effect_col, "Number")
            .and_then(text)
            .unwrap_or_else(|| "00".to_string());
        let value = find_child(effect_col, "Value")
            .and_then(text)
            .unwrap_or_else(|| "00".to_string());

        let idx = row * num_master_track_columns;
        if let Some(cell) = out.get_mut(idx) {
            cell.effect_number = number;
            cell.effect_value = value;
        }
    }
}

fn extract_instrument(instrument: Node) -> InstrumentData {
    let mut data = InstrumentData {
        name: find_child(instrument, "Name")
            .and_then(text)
            .unwrap_or_default(),
        ..Default::default()
    };

    let Some(sample_generator) = find_child(instrument, "SampleGenerator") else {
        return data;
    };

    extract_envelopes(sample_generator, &mut data);

    if let Some(samples_node) = find_child(sample_generator, "Samples") {
        let sample_nodes: Vec<Node> = samples_node
            .children()
            .filter(|c| c.has_tag_name("Sample"))
            .collect();

        for (sample_index, sample_node) in sample_nodes.iter().enumerate() {
            data.samples.push(extract_sample(*sample_node));

            if let Some(mapping) = find_child(*sample_node, "Mapping") {
                let note_start: i32 = find_child(mapping, "NoteStart")
                    .and_then(text)
                    .and_then(|s| s.parse().ok())
                    .unwrap_or(0);
                let note_end: i32 = find_child(mapping, "NoteEnd")
                    .and_then(text)
                    .and_then(|s| s.parse().ok())
                    .unwrap_or(119);

                for note in note_start.max(0)..=note_end.min(119) {
                    data.key_map[note as usize] = Some(sample_index as u8);
                }
            }
        }
    }

    data
}

fn extract_sample(sample: Node) -> SampleData {
    let mut data = SampleData::new();

    data.name = find_child(sample, "Name")
        .and_then(text)
        .unwrap_or_default();
    data.loop_start = find_child(sample, "LoopStart")
        .and_then(text)
        .and_then(|s| s.parse().ok())
        .unwrap_or(0);
    data.loop_end = find_child(sample, "LoopEnd")
        .and_then(text)
        .and_then(|s| s.parse().ok())
        .unwrap_or(0);
    data.loop_mode = match find_child(sample, "LoopMode").and_then(text).as_deref() {
        Some("Forward") => LoopMode::Forward,
        Some("PingPong") | Some("Backward") => LoopMode::PingPong,
        _ => LoopMode::Off,
    };
    data.volume = find_child(sample, "Volume")
        .and_then(text)
        .and_then(|s| s.parse::<f32>().ok())
        .unwrap_or(1.0)
        .abs();
    data.panning = find_child(sample, "Panning")
        .and_then(text)
        .and_then(|s| s.parse().ok())
        .unwrap_or(0.5);
    data.fine_tune = find_child(sample, "FineTune")
        .and_then(text)
        .and_then(|s| s.parse().ok())
        .unwrap_or(0);
    data.transpose = find_child(sample, "Transpose")
        .and_then(text)
        .and_then(|s| s.parse().ok())
        .unwrap_or(0);
    data.rel_note_number = find_child(sample, "Mapping")
        .and_then(|m| find_child(m, "BaseNote"))
        .and_then(text)
        .and_then(|s| s.parse().ok())
        .unwrap_or(DEFAULT_BASE_NOTE);

    data
}

/// The Renoise schema has changed how instrument envelopes are represented at least once. This
/// handles both known device shapes; see the module-level docs for the `/10.665` rescale used by
/// the newer shape (reverse-engineered in the original from real files, not principled).
fn extract_envelopes(sample_generator: Node, data: &mut InstrumentData) {
    const NEWER_SCHEMA_POINT_DIVISOR: f32 = 10.665;

    let Some(mod_sets) = find_child(sample_generator, "ModulationSets") else {
        return;
    };
    let Some(mod_set) = find_child(mod_sets, "ModulationSet") else {
        return;
    };
    let Some(devices) = find_child(mod_set, "Devices") else {
        return;
    };

    for device in devices.children() {
        let (is_older_shape, is_newer_shape) = (
            device.has_tag_name("SampleCompatibilityModulationDevice"),
            device.has_tag_name("SampleEnvelopeModulationDevice"),
        );
        if !is_older_shape && !is_newer_shape {
            continue;
        }

        let target = find_child(device, "Target")
            .and_then(text)
            .unwrap_or_default();
        let envelope = match target.as_str() {
            "Volume" => &mut data.volume_envelope,
            "Panning" => &mut data.panning_envelope,
            _ => continue,
        };

        *envelope = EnvelopeData {
            enabled: find_child(device, "IsActive")
                .and_then(text)
                .map(|s| s == "true")
                .unwrap_or(false),
            fade_out: find_child(device, "FadeOut")
                .and_then(text)
                .and_then(|s| s.parse().ok())
                .unwrap_or(0),
            sustain_enabled: find_child(device, "SustainEnabled")
                .and_then(text)
                .map(|s| s == "true")
                .unwrap_or(false),
            loop_enabled: find_child(device, "LoopMode")
                .and_then(text)
                .map(|s| s != "Off")
                .unwrap_or(false),
            ..Default::default()
        };

        let divisor = if is_newer_shape {
            NEWER_SCHEMA_POINT_DIVISOR
        } else {
            1.0
        };

        if let Some(points_node) = find_child(device, "Points") {
            envelope.points = points_node
                .children()
                .filter(|c| c.has_tag_name("Point"))
                .filter_map(text)
                .filter_map(|s| parse_point(&s, divisor))
                .collect();
        }

        envelope.sustain_point_x = find_child(device, "SustainPosition")
            .and_then(text)
            .and_then(|s| s.parse::<f32>().ok())
            .map(|x| x / divisor)
            .unwrap_or(0.0);
        envelope.loop_start_x = find_child(device, "LoopStart")
            .and_then(text)
            .and_then(|s| s.parse::<f32>().ok())
            .map(|x| x / divisor)
            .unwrap_or(0.0);
        envelope.loop_end_x = find_child(device, "LoopEnd")
            .and_then(text)
            .and_then(|s| s.parse::<f32>().ok())
            .map(|x| x / divisor)
            .unwrap_or(0.0);
    }
}

/// Parses a Renoise `"x,y"` envelope point string, rescaling `x` by `divisor`.
fn parse_point(s: &str, divisor: f32) -> Option<(f32, f32)> {
    let (x, y) = s.split_once(',')?;
    let x: f32 = x.trim().parse().ok()?;
    let y: f32 = y.trim().parse().ok()?;
    Some((x / divisor, y))
}
